# Server config
server:
  port: ${PORT:8098}

# Spring config
spring:
  application:
    name: front-end-service
  logging:
    level:
      org.springframework: WARN
      org.hibernate: WARN